import SVGExport from "@/components/svgs/SVGExport";
import CustomTable from "@/components/table";
import { Button, Divider, Heading, Text } from "@chakra-ui/react";
import { ColumnDef } from "@tanstack/react-table";

type Person = {
  name: number;
  orders: string[];
  personalCode: number;
  number: string;
};

const data: Person[] = [
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "0",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "1",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "2",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "3",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "4",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "5",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "6",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "7",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "8",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "9",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "10",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "11",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "12",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "13",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "14",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "15",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "16",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "17",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "18",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "19",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "20",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "21",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "22",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "23",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "24",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "25",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "26",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "27",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "28",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "29",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "30",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "31",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "32",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "33",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "34",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "35",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "36",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "37",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "38",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "39",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "40",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "41",
  },

  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "106",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "107",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "108",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "109",
  },
  {
    name: 1,
    orders: [
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
      "Alice",
    ],
    personalCode: 25,
    number: "110",
  },
  {
    name: 2,
    orders: [
      "Bob",
      "Bob",
      "Bob",
      "Bob",
      "Bob",
      "Bob",
      "Bob",
      "Bob",
      "Bob",
      "Bob",
    ],
    personalCode: 30,
    number: "111",
  },
];

const OrderDetail = () => {
  const columns: ColumnDef<Person>[] = [
    {
      accessorKey: "name",
      header: "نام پرسنل",

      cell: (info) => info.getValue(), // Automatically types info based on `Person`
    },
    {
      accessorKey: "personalCode",
      header: "کد پرسنل",
      cell: (info) => <div className="w-full">{(info as any).getValue()}</div>,
    },
    {
      accessorKey: "orders",
      header: "سفارش ها",
      accessorFn: (row) => row.orders,
      cell: (info) => {
        return (
          <div className=" flex ">
            {(info as any)?.getValue()?.map((item: any, index: number) => (
              <>
                <Text className={` pl-22 flex items-center justify-center `}>
                  {item}
                  {index + 1 !== (info as any).getValue().length && (
                    <Divider orientation="vertical" className="px-8" />
                  )}
                </Text>
              </>
            ))}
          </div>
        );
      },
    },
  ];
  return (
    <div className="bg-white min-h-full rounded-lg px-24 py-18 flex flex-col space-y-10 justify-between">
      <div className="w-full flex justify-between items-center">
        <div>
          <Heading className="!text-18 !font-bold !px-16 !py-8">
            جزییات سفارش
          </Heading>
        </div>
        <div className="flex justify-between gap-12">
          <div className="w-full">
            {" "}
            <Button size={"md"} className="flex items-center gap-8 px-16 py-8">
              <SVGExport />
              خروجی اکسل{" "}
            </Button>
          </div>
        </div>
      </div>
      <CustomTable
        metadata={{
          total: data.length,
        }}
        columns={columns}
        data={data}
        search={{
          placeholder: "جستجو......",
        }}
      />
    </div>
  );
};

export default OrderDetail;
